version: '3.1'

services:
  database:
    image: mongo
    container_name: finance-app-db
    ports:
      - 27017:27017
    networks:
      - finance-app-network
  authorization-service:
    container_name: authorization-service
    build:
      context: './api/authorization'
      dockerfile: Dockerfile
    environment:
      env_file: .env
      NODE_ENV: production
    volumes:
      - ./api/authorization:/home/node/api/authorization
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - finance-app-network
  account-service:
    container_name: account-service
    build:
      context: './api/account'
      dockerfile: Dockerfile
    environment:
      env_file: .env
      NODE_ENV: production
    volumes:
      - ./api/account:/home/node/api/account
    ports:
      - 8081:8081
    depends_on:
      - database
      - authorization-service
    networks:
      - finance-app-network
  finance-app:
    container_name: finance-app
    build:
      context: './app/finance-app'
      dockerfile: Dockerfile
    volumes:
      - ./app/finance-app:/home/node/app
    ports:
      - 4200:80
    depends_on:
      - database
      - account-service
      - authorization-service
networks:
  finance-app-network:
    driver: bridge
