version: '3.1'

services:
  database:
    image: mongo
    container_name: finance-app-db
    restart: always
    ports:
      - 27017:27017
    networks:
      - finance-app-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: 'finance-app-db'
    ports:
      - 8081:8081
    networks:
      - finance-app-network
    depends_on:
      - database
  api-service:
    container_name: api-service
    build:
      context: './api/'
      dockerfile: Dockerfile
    environment:
      env_file: .env
      NODE_ENV: production
    volumes:
      - ./api/:/home/node/api/
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - finance-app-network
  finance-app:
    container_name: finance-app
    build:
      context: './app/finance-app'
      dockerfile: Dockerfile
    volumes:
      - ./app/finance-app:/home/node/app
    ports:
      - 4200:80
    depends_on:
      - database
      - api-service
networks:
  finance-app-network:
    driver: bridge
