/* eslint-disable no-unused-vars */
export enum ComboBoxProcessType {
  ACCOUNT_SEARCH = 'ACCOUNT_SEARCH',
  CATEGORY_SEARCH_OR_CREATE = 'CATEGORY_SEARCH_OR_CREATE',
  GROUP_SEARCH_OR_CREATE = 'GROUP_SEARCH_OR_CREATE',
  EVENT_SEARCH_OR_CREATE = 'EVENT_SEARCH_OR_CREATE',
  PROJECT_SEARCH_OR_CREATE = 'PROJECT_SEARCH_OR_CREATE',
  PRODUCT_SEARCH_OR_CREATE = 'PRODUCT_SEARCH_OR_CREATE',
  TARGET_SEARCH_OR_CREATE = 'TARGET_SEARCH_OR_CREATE',
}
